export enum Action{
    TOGGLE_TV_SWITCH = 'TOGGLE_TV_SWITCH',
    INCREASE_SOUND_SYSTEM_VOLUME = 'INCREASE_SOUND_SYSTEM_VOLUME',
    DECREASE_SOUND_SYSTEM_VOLUME = 'DECREASE_SOUND_SYSTEM_VOLUME',
    INCREASE_FRIDGE_TEMP = 'INCREASE_FRIDGE_TEMP',
    DECREASE_FRIDGE_TEMP = 'DECREASE_FRIDGE_TEMPERATURE',
    INCREASE_FAN_ROTATION_SPEED = 'INCREASE_FAN_ROTATION_SPEED',
    DECREASE_FAN_ROTATION_SPEED = 'DECREASE_FAN_ROTATION_SPEED',
    CHANGE_LIGHTS_BRIGHTNESS_LEVEL = 'CHANGE_LIGHTS_BRIGHTNESS_LEVEL'
}